### ISSUE TITLE
Dialogue System

### ISSUE THREAD

**Issue by Zerhadow** [Zerhadow/Project-Dragon-Drama#1]
- [x] When talking (press intereact) to NPC, diaglog bubble shows. 
- [x] When player is talking to mean girls, call dialogue overlay (cutscene) and trigger dialogue
- [x] Ability to store dialog lines in single script. Must be public for all other scripts
- [ ] Ability to Skip dialogue
- [x] Dialogue options

**Comment by WaywardKoyote** [comment]
Dialogue will be composed of 3 parts: Left character, Right character, and text. We'll need to be able to update these separately for each text block so we should have each dialogue set stored as an array of these 3 elements. We can use a hash map or just a large switch case for selecting which dialogue array to go through.
